### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by chilblane** [bitjourney/react-simple-image#15]
I'm getting a console warning using this component that React.PropTypes is being used instead of the separate [prop-types](https://github.com/facebook/prop-types) package. I noticed you're currently importing everything from the React package; this might be worth a look.

**Comment by kenju** [comment]
@chilblane Thanks for opening this issue. I am working on it asap!

**Comment by kenju** [comment]
@chilblane 
I have just published a new package, and now it is available with `v0.2.0`.
( resolved at https://github.com/bitjourney/react-simple-image/pull/16 )
